# -*- coding: utf-8 -*-
"""Wildlife_image_classification_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sr8wC1bllkKR7DG6jSgDHUw2w8Tv5wW
"""



!pip install -q torchinfo

import os
import sys
from collections import Counter

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import PIL
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
from torch.utils.data import DataLoader, random_split
from torchinfo import summary
from torchvision import datasets, transforms
from tqdm.notebook import tqdm

torch.backends.cudnn.deterministic = True

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"

print(f"Using {device} device.")

print("Platform:", sys.platform)
print("Python version:", sys.version)
print("---")
print("matplotlib version:", matplotlib.__version__)
print("pandas version:", pd.__version__)
print("PIL version:", PIL.__version__)
print("torch version:", torch.__version__)
print("torchvision version:", torchvision.__version__)

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/My Drive/wildlife_hog.zip" -d "/content/wildlife_hog"

!unzip "/content/drive/My Drive/wildlife_monkey.zip" -d "/content/wildlife_monkey"

!unzip "/content/drive/My Drive/wildlife_leopard.zip" -d "/content/wildlife_leopard"

!unzip "/content/drive/My Drive/wildlife_civetgenet.zip" -d "/content/wildlife_civetgenet"

!unzip "/content/drive/My Drive/wildlife_antelope_duikers.zip" -d "/content/wildlife_antelope_duikers"

!unzip "/content/drive/My Drive/wildlife_rodent.zip" -d "/content/wildlife_rodent"

!unzip "/content/drive/My Drive/wildlife_birds.zip" -d "/content/wildlife_birds"

!unzip "/content/drive/My Drive/wildlife_blank.zip" -d "/content/wildlife_blank"

!unzip "/content/drive/My Drive/test_features.zip" -d "/content/test"

import os
print(os.listdir("/content"))

import os
import shutil

# Step 1: Create root directory structure
root_dir = "/content/data/data_multiclass"
train_dir = os.path.join(root_dir, "train")
test_dir = os.path.join(root_dir, "test")
test_features_dir = os.path.join(test_dir, "test_features")

os.makedirs(train_dir, exist_ok=True)
os.makedirs(test_dir, exist_ok=True)
os.makedirs(test_features_dir, exist_ok=True)

# Step 2: Create class subdirectories inside train/
class_dirs = {
    "hog": os.path.join(train_dir, "wildlife_hog"),
    "blank": os.path.join(train_dir, "wildlife_blank"),
    "leopard": os.path.join(train_dir, "wildlife_leopard"),
    "monkey": os.path.join(train_dir, "wildlife_monkey"),
    "birds": os.path.join(train_dir, "wildlife_birds"),
    "civetgenet": os.path.join(train_dir, "wildlife_civetgenet"),
    "antelope_duikers": os.path.join(train_dir, "wildlife_antelope_duikers"),
    "rodent": os.path.join(train_dir, "wildlife_rodent")
}

for path in class_dirs.values():
    os.makedirs(path, exist_ok=True)

# Step 3: Copy images into their respective class folders

# hog
for filename in os.listdir("/content/wildlife_hog"):
    src = os.path.join("/content/wildlife_hog", filename)
    dst = os.path.join(class_dirs["hog"], filename)
    shutil.copy2(src, dst)

# blank
for filename in os.listdir("/content/wildlife_blank"):
    src = os.path.join("/content/wildlife_blank", filename)
    dst = os.path.join(class_dirs["blank"], filename)
    shutil.copy2(src, dst)

# leopard
for filename in os.listdir("/content/wildlife_leopard"):
    src = os.path.join("/content/wildlife_leopard", filename)
    dst = os.path.join(class_dirs["leopard"], filename)
    shutil.copy2(src, dst)

# monkey
for filename in os.listdir("/content/wildlife_monkey"):
    src = os.path.join("/content/wildlife_monkey", filename)
    dst = os.path.join(class_dirs["monkey"], filename)
    shutil.copy2(src, dst)

# birds (nested inside birds/)
for filename in os.listdir("/content/wildlife_birds/birds"):
    src = os.path.join("/content/wildlife_birds/birds", filename)
    dst = os.path.join(class_dirs["birds"], filename)
    shutil.copy2(src, dst)

# civetgenet
for filename in os.listdir("/content/wildlife_civetgenet"):
    src = os.path.join("/content/wildlife_civetgenet", filename)
    dst = os.path.join(class_dirs["civetgenet"], filename)
    shutil.copy2(src, dst)

# antelope_duikers (nested inside antelope duikers/)
for filename in os.listdir("/content/wildlife_antelope_duikers/antelope duikers"):
    src = os.path.join("/content/wildlife_antelope_duikers/antelope duikers", filename)
    dst = os.path.join(class_dirs["antelope_duikers"], filename)
    shutil.copy2(src, dst)

# rodent
for filename in os.listdir("/content/wildlife_rodent"):
    src = os.path.join("/content/wildlife_rodent", filename)
    dst = os.path.join(class_dirs["rodent"], filename)
    shutil.copy2(src, dst)

# Step 4: Copy test images into testdata/
test_img_dir = "/content/test"
for filename in os.listdir(test_img_dir):
    if filename.lower().endswith(('.jpg', '.jpeg', '.png')):
        src = os.path.join(test_img_dir, filename)
        dst = os.path.join(test_features_dir, filename)
        shutil.copy2(src, dst)

# Step 5: Copy CSV files into test/
csv_files = ["submission_format.csv", "test_features.csv"]
for csv_file in csv_files:
    src = os.path.join("/content", csv_file)
    dst = os.path.join(test_dir, csv_file)
    if os.path.exists(src):
        shutil.copy2(src, dst)
    else:
        print(f"⚠️ CSV file missing: {csv_file}")

train_dir = os.path.join(root_dir, 'train')


print("Will read data from", train_dir)

labels = os.listdir(train_dir)
labels

hog_path = os.path.join(train_dir, "wildlife_hog")
hog_images = os.listdir(hog_path)
print("length of hog images: ", len(hog_images))

blank_path = os.path.join(train_dir, "wildlife_blank")
blank_images = os.listdir(blank_path)
print("length of blank images: ", len(blank_images))

leopard_path = os.path.join(train_dir, "wildlife_leopard")
leopard_images = os.listdir(leopard_path)
print("length of leopard images: ", len(leopard_images))

monkey_path = os.path.join(train_dir, "wildlife_monkey")
monkey_images = os.listdir(monkey_path)
print("length of monkey images: ", len(monkey_images))

birds_path = os.path.join(train_dir, "wildlife_birds")
birds_images = os.listdir(birds_path)
print("length of birds images: ", len(birds_images))

civetgenet_path = os.path.join(train_dir, "wildlife_civetgenet")
civetgenet_images = os.listdir(civetgenet_path)
print("length of civetgenet images: ", len(civetgenet_images))

antelope_duikers_path = os.path.join(train_dir, "wildlife_antelope_duikers")
antelope_duikers_images = os.listdir(antelope_duikers_path)
print("length of antelope_duikers images: ", len(antelope_duikers_images))

rodent_path = os.path.join(train_dir, "wildlife_rodent")
rodent_images = os.listdir(rodent_path)
print("length of rodent images: ", len(rodent_images))

class ConvertToRGB:
    def __call__(self, img):
        if img.mode != "RGB":
            img = img.convert("RGB")
        return img



import timm
from timm import create_model

# Choose EfficientNetB3 or B4
model = create_model('efficientnet_b3', pretrained=True, num_classes=8)
# model = create_model('efficientnet_b4', pretrained=True, num_classes=8)  # optional

model.to(device)

from torchvision import transforms

transform = transforms.Compose([
    ConvertToRGB(),
    transforms.Resize((300, 300)),  # EfficientNet prefers 300x300
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],  # Standard ImageNet mean
        std=[0.229, 0.224, 0.225]
    )
])

from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader, random_split

# Replace with your path
train_path = "/content/data/data_multiclass/train"

dataset = ImageFolder(train_path, transform=transform)

g = torch.Generator().manual_seed(42)
train_dataset, val_dataset = random_split(dataset, [0.8, 0.2], generator=g)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)

from torch.optim import AdamW
optimizer = AdamW(model.parameters(), lr=0.0003, weight_decay=1e-4)
criterion = nn.CrossEntropyLoss()

from tqdm import tqdm
import torch

def train_model(model, train_loader, val_loader, criterion, optimizer, device, epochs=10):
    train_losses = []
    val_accuracies = []

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0

        # tqdm for training progress
        loop = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs} [Training]", leave=False)
        for images, labels in loop:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * images.size(0)
            loop.set_postfix(loss=loss.item())

        epoch_loss = running_loss / len(train_loader.dataset)
        train_losses.append(epoch_loss)

        # Validation accuracy
        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                _, predicted = torch.max(outputs, 1)
                total += labels.size(0)
                correct += (predicted == labels).sum().item()

        val_acc = correct / total
        val_accuracies.append(val_acc)

        print(f" Epoch {epoch+1}: Loss = {epoch_loss:.4f}, Val Accuracy = {val_acc:.4f}")

    return train_losses, val_accuracies

import matplotlib.pyplot as plt

train_loss, val_acc = train_model(model, train_loader, val_loader, criterion, optimizer, device, epochs=8)

plt.plot(val_acc, label="Validation Accuracy", marker='o')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Validation Accuracy Over Epochs")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Get predictions
model.eval()
all_preds, all_labels = [], []

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        labels = labels.to(device)
        outputs = model(images)
        preds = torch.argmax(outputs, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

# Confusion Matrix
cm = confusion_matrix(all_labels, all_preds)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=dataset.classes)
disp.plot(cmap="Blues", xticks_rotation="vertical")
plt.title("Confusion Matrix")
plt.grid(False)
plt.show()

# Classification Report (F1, Recall, Precision)
print(classification_report(all_labels, all_preds, target_names=dataset.classes))

plt.figure(figsize=(12,5))

plt.subplot(1, 2, 1)
plt.plot(train_loss, label='Train Loss', marker='o')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Training Loss")
plt.grid(True)
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(val_acc, label='Val Accuracy', marker='o', color='green')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Validation Accuracy")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

# Save entire model
torch.save(model, "efficient_netb3.pth")

# Copy to Drive
!cp efficient_netb3.pth /content/drive/MyDrive/efficient_netb3.pth

import torch

model = torch.load("/content/drive/MyDrive/efficient_netb3.pth", weights_only=False)
model.eval().to(device)

transform = transforms.Compose([
    ConvertToRGB(),
    transforms.Resize((300, 300)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

from PIL import Image
import torch.nn.functional as F

def predict_single_image(image_path, model, transform, class_names, device):
    model.eval()
    image = Image.open(image_path).convert("RGB")
    input_tensor = transform(image).unsqueeze(0).to(device)

    with torch.no_grad():
        output = model(input_tensor)
        probs = F.softmax(output, dim=1)
        pred_idx = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred_idx].item()

    predicted_class = class_names[pred_idx]
    return predicted_class, confidence

image_path = "/content/data/data_multiclass/test/test_features/ZJ016930.jpg"

predicted_class, confidence = predict_single_image(
    image_path,
    model,
    transform,
    dataset.classes,
    device
)

print(f" Predicted Class: {predicted_class}")
print(f" Confidence: {confidence:.4f}")


import matplotlib.pyplot as plt

img = Image.open(image_path)
plt.imshow(img)
plt.title(f"Predicted: {predicted_class}\nConfidence: {confidence:.2f}")
plt.axis('off')
plt.show()